PKG_NAME := pypi-tifffile
URL = https://files.pythonhosted.org/packages/5f/69/5a1ac32c12255d63d7247c3b068e900c1d473dc9a6c9dd6666fd9091a2cb/tifffile-2023.2.2.tar.gz
ARCHIVES = 

include ../common/Makefile.common
